version: '3.7'

# example docker-compose

services:
  app:
    build: martlark
    ports:
      - "18008:80"
    volumes:
      - ./persist:/persist
    environment:
      GUNICORN_THREADS: 4
    restart: unless-stopped

